spring:
  datasource:
    url: jdbc:mysql://localhost:3308/dbslide
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
  profiles:
    active: api


